### ISSUE TITLE
Тест на корректность деструктора у помувнутого фанкшн

### ISSUE THREAD

**Issue by lejabque** [CPP-KT/function-task#2]
- Если там лежал small, то у него должен быть вызван когда-нибудь деструктор
- Если там лежал big, то нужно не допускать дважды delete (из нового и старого фанкшна)

**Comment by dedlocc** [comment]
[39a87a4](https://github.com/CPP-KT/function-task/commit/39a87a48930cd60f716cfedd9706d668191698fd)
